install.packages("rJava")
install.packages("memoise")
install.packages("KoNLP")
library(KoNLP)
library(dplyr)
useNIADic()
txt <- readLines("hiphop.txt")
head(txt)
install.packages("stringr")
library(stringr)
txt <- str_replace_all(txt, "\\W", " ")
nouns <- extractNoun(txt)
wordcount <- table(unlist(nouns))
df_word <- as.data.frame(wordcount, stringsAsFactors = F)
df_word <- rename(df_word, word=Var1, freq=Freq)
install.packages("ggplot2")
library(ggplot2)
names(df_word)
df_word <- filter(df_word, nchar(word) >= 2)
df_word
top_20 <- df_word %>% arrange(desc(freq)) %>% head(20)
top_20
install.packages("wordcloud")
library(wordcloud)
install.packages("RcolorBrewer")
library(RColorBrewer)
pal <- brewer.pal(8, "Dark2")
set.seed(1234)
wordcloud(words = df_word$word, freq = df_word$freq, min.freq = 2, max.words = 200, random.order = F, 
          rot.per = .1, scale = c(4, 0.3), colors = pal)
pal<- brewer.pal(9, "Blues")[5:9]
set.seed(1234)
wordcloud(words = df_word$word, freq = df_word$freq, min.freq = 2, max.words = 200, random.order = F, 
          rot.per = .1, scale = c(4, 0.3), colors = pal)
